# Generated by Django 2.2.1 on 2019-05-23 12:00

from django.db import migrations, models
import todo_rest_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Task Title', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Task Description', null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Task image', upload_to='images/', verbose_name='Image')),
                ('due', models.DateTimeField(default=todo_rest_api.models.days_from_now_1, help_text='Task Due (default - 1 day from now)', verbose_name='due')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
